services:
  - type: web
    name: nom-035-prototype
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /resultados-nom035.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: FEEDBACK_ENABLED
        value: true